CREATE SCHEMA mascotasLujo;
use mascotasLujo;
CREATE TABLE clientes(
	id INT(5) PRIMARY KEY AUTO_INCREMENT,
	login VARCHAR(50) UNIQUE NOT NULL,
	nome VARCHAR(100) NOT NULL,
	email VARCHAR(60) NOT NULL,
	CPF VARCHAR(14) UNIQUE NOT NULL,
	telefone VARCHAR(14) UNIQUE NOT NULL,
	endereco VARCHAR(100) NOT NULL
);
CREATE TABLE senhas(
	id INT(5) PRIMARY KEY AUTO_INCREMENT,
	cliente INT(5),
	FOREIGN KEY(cliente) REFERENCES clientes(id)
);